version: "3"
services:
  ######################################################
  ## ミドルウェア 
  ######################################################
  # ec2 ################################################
  ec2:
    build: ./docker/ec2
    volumes:
      - "./ansible:/ansible"
    ports:
      - "80:80"
    tty: true
    privileged: true
  # MySQL ################################################
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    expose:
      - "3306"
    volumes:
      - "./.data/mysql:/var/lib/mysql"
      - "./log/mysql:/var/log/mysql"
    ports:
      - "3306:3306"
  # Nginx ################################################
  nginx:
    build: ./docker/nginx
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - php-fpm
      - laravel
    volumes:
      - "./web:/var/www/web:cached"
      - "./log/nginx:/var/log/nginx"
    ports:
      - "80:80"
  ######################################################
  ## 言語 
  ######################################################
  # php-fpm ################################################
  php-fpm:
    build: ./docker/php-fpm
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./web:/var/www/web:cached"
    tty: true
  # python ################################################
  python:
    build: ./docker/python
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./web:/var/www/web:cached"
    tty: true
  # golang ################################################
  golang:
    build: ./docker/golang
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./web:/var/www/web:cached"
    tty: true
  # ruby ################################################
  ruby:
    build: ./docker/ruby
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./web:/var/www/web:cached"
    tty: true
  ######################################################
  ## フレームワーク 
  ######################################################
  # laravel ################################################
  laravel:
    build: ./docker/laravel
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./web:/var/www/web:cached"
    tty: true