version: "3"
services:
  # ec2 ################################################
  ec2:
    build: ./docker/ec2
    volumes:
      - "./ansible:/ansible"
      - "./www:/var/www:cached"
    tty: true
    privileged: true
  # MySQL ################################################
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    expose:
      - "3306"
    command: 
      - "--character-set-server=utf8"
      # - "--default-authentication-plugin=mysql_native_password" # MySQL 8.0使用時に必要
    volumes:
      - "./.data/mysql:/var/lib/mysql"
      - "./log/mysql:/var/log/mysql"
    ports:
      - "3306:3306"
  # php-fpm ################################################
  php-fpm:
    build: ./docker/php-fpm
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./www:/var/www:cached"
    tty: true
  # python ################################################
  python:
    build: ./docker/python
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./www:/var/www:cached"
    tty: true
  # golang ################################################
  golang:
    build: ./docker/golang
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./www:/var/www:cached"
    tty: true
  # ruby ################################################
  ruby:
    build: ./docker/ruby
    depends_on:
      - mysql
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
    volumes:
      - "./www:/var/www:cached"
    tty: true
