---
- name: Install modules for rbenv
  yum:
    state: present
    name:
      - tar
      - git
      - gcc
      - openssl-devel
      - readline-devel
      - zlib-devel

- name: Git clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
    version: master

- name: Setting .bash_profile
  shell: |
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    source ~/.bash_profile

- name: Git clone ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    version: master

- name: Install Ruby3.0
  shell: /bin/bash -lc "rbenv install 3.0.0 && rbenv global 3.0.0"

- name: Install modules
  yum:
    state: present
    name:
      - ruby-devel
