---
- name: Install Ruby
  shell: amazon-linux-extras install -y ruby2.6

- name: Install modules
  yum:
    state: present
    name:
      - ruby-devel

- name: Install bundler
  gem:
    user_install: no
    state: present
    name: bundler

- name: Install mysql2
  gem:
    user_install: no
    state: present
    name: mysql2
