---
- name: Install common modules
  yum:
    state: present
    name:
      - mariadb-devel
      - gcc
      - git

- name: Deploy .bash_profile
  template:
    src: templates/.bash_profile
    dest: /root/.bash_profile
