---
- name: Install Go
  # リポジトリに表示されるトピックとバージョンは異なる場合があるらしい。実際バージョンがgo1.15.3だった
  shell: amazon-linux-extras install -y golang1.11

- name: Go get go-sql-driver/mysql
  shell: go get -u github.com/go-sql-driver/mysql