---
- hosts: all
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
    - role: common
      tags: common
    - role: clone
      tags: clone
    - role: mysql
      tags: mysql
    - role: go
      tags: go
    - role: php
      tags: php
    - role: ruby
      tags: ruby
    - role: python
      tags: python
    # - nginx # webサーバーとして確認する場合
